clean_zone:
  description: Start the cleaning operation in the selected areas for the number of repeats indicated.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    zone:
      description: Array of zones. Each zone is an array of 4 float values. The values are in meters, where (0, 0) is the robot attached to the docking station.
      example: "[[-1,-1,2,2]]"
    repeats:
      description: Number of cleaning repeats for each zone between 1 and 3.
      example: "1"

goto:
  description: Start cleaning around the specified coordinate (spot cleaning).
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    x_coord:
      description: x-coordinate.
      example: "-1"
    y_coord:
      description: y-coordinate.
      example: 2

clean_segment:
  description: Start cleaning of the specified segment(s).
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    segments:
      description: Segments.
      example: "[10,11]"

clean_area:
  description: Start the cleaning operation in the selected areas for the number of repeats indicated.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    area:
      description: Array of areas. Each area is an array of 8 integer values (4 points).
      example: "[[23510,25311,25110,26362]]"
    repeats:
      description: Number of cleaning repeats for each zone between 1 and 3.
      example: "1"

clean_point:
  description: Start the cleaning operation by selected point.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    point:
      description: Point.
      example: "[23510,25311]"
